FROM ghcr.io/phpstan/phpstan:latest-php8.2

RUN apk update --progress --no-cache
RUN apk add icu-dev libxml2-dev libzip-dev
RUN apk add --no-cache linux-headers
RUN docker-php-ext-install intl soap mysqli sockets xml zip

# Composer
# renovate: datasource=github-tags depName=composer/composer versioning=semver
ENV COMPOSER_VERSION="2.6.5"
RUN curl -sfL https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer
RUN chmod +x /usr/bin/composer
RUN composer self-update --clean-backups ${COMPOSER_VERSION}

# Openswoole
# renovate: datasource=github-tags depName=openswoole/swoole-src versioning=semver
ENV OPENSWOOLE_VERSION="v22.1.1"
RUN apk update
RUN apk add --no-cache linux-headers
RUN apk add --no-cache libstdc++ postgresql-dev libpq
RUN apk add --no-cache --virtual .build-deps $PHPIZE_DEPS curl-dev openssl-dev pcre-dev pcre2-dev zlib-dev
RUN docker-php-ext-install sockets
RUN docker-php-source extract
RUN mkdir /usr/src/php/ext/openswoole
RUN curl -sfL https://github.com/openswoole/swoole-src/archive/${OPENSWOOLE_VERSION}.tar.gz -o swoole.tar.gz
RUN tar xfz swoole.tar.gz --strip-components=1 -C /usr/src/php/ext/openswoole
RUN docker-php-ext-configure openswoole \
        --enable-http2 \
        --enable-mysqlnd \
        --enable-openssl \
        --enable-sockets \
        --enable-hook-curl \
        --with-postgres
RUN docker-php-ext-install -j$(nproc) --ini-name zzz-docker-php-ext-openswoole.ini openswoole
RUN rm -f swoole.tar.gz $HOME/.composer/*-old.phar
RUN docker-php-source delete
RUN apk del .build-deps

# Redis
# renovate: datasource=github-tags depName=phpredis/phpredis versioning=semver
ENV PHP_REDIS_VERSION="6.0.0"
RUN apk add --no-cache pcre-dev $PHPIZE_DEPS
RUN pecl install redis-${PHP_REDIS_VERSION}
RUN docker-php-ext-enable redis.so