FROM ghcr.io/phpstan/phpstan:latest-php8.3@sha256:a667df996e260e42c91451d5146d5934f53aafc44e5c2546ec374243866ee8d0

RUN apk update --progress --no-cache
RUN apk add icu-dev libxml2-dev libzip-dev
RUN apk add --no-cache linux-headers
RUN docker-php-ext-install intl soap mysqli sockets xml zip

# Composer
# renovate: datasource=github-tags depName=composer/composer versioning=semver
ENV COMPOSER_VERSION="2.8.10"
RUN curl -sfL https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer
RUN chmod +x /usr/bin/composer
RUN composer self-update --clean-backups ${COMPOSER_VERSION}

# Openswoole
# renovate: datasource=github-tags depName=openswoole/swoole-src versioning=semver
ENV OPENSWOOLE_VERSION="v25.2.0"
RUN apk update
RUN apk add --no-cache linux-headers
RUN apk add --no-cache libstdc++ postgresql-dev libpq liburing liburing-dev
RUN apk add --no-cache --virtual .build-deps $PHPIZE_DEPS curl-dev openssl-dev pcre-dev pcre2-dev zlib-dev
RUN docker-php-ext-install sockets
RUN docker-php-source extract
RUN cd /tmp && git clone https://github.com/openswoole/ext-openswoole.git
WORKDIR /tmp/ext-openswoole
RUN git checkout ${OPENSWOOLE_VERSION}
RUN phpize
RUN ./configure --enable-openssl --enable-hook-curl --enable-http2 --enable-mysqlnd
RUN make
RUN make install

RUN touch /usr/local/etc/php/conf.d/openswoole.ini && \
    echo 'extension=openswoole.so' > /usr/local/etc/php/conf.d/zzz_openswoole.ini

# Redis
# renovate: datasource=github-tags depName=phpredis/phpredis versioning=semver
ENV PHP_REDIS_VERSION="6.2.0"
RUN apk add --no-cache pcre-dev $PHPIZE_DEPS
RUN pecl install redis-${PHP_REDIS_VERSION}
RUN docker-php-ext-enable redis.so

WORKDIR /app