FROM ghcr.io/phpstan/phpstan:latest-php8.1@sha256:13e2048d0a4d7c36db54c773fac6e7e78952ae10f344d5dd6205200c8be1d2b1

RUN apk update --progress --no-cache
RUN apk add icu-dev libxml2-dev libzip-dev
RUN apk add --no-cache linux-headers
RUN docker-php-ext-install intl soap mysqli sockets xml zip

# Composer
# renovate: datasource=github-tags depName=composer/composer versioning=semver
ENV COMPOSER_VERSION="2.8.5"
RUN curl -sfL https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer
RUN chmod +x /usr/bin/composer
RUN composer self-update --clean-backups ${COMPOSER_VERSION}

# Openswoole
ENV OPENSWOOLE_VERSION="v22.1.2"
RUN apk update
RUN apk add --no-cache linux-headers
RUN apk add --no-cache libstdc++ postgresql-dev libpq
RUN apk add --no-cache --virtual .build-deps $PHPIZE_DEPS curl-dev openssl-dev pcre-dev pcre2-dev zlib-dev
RUN docker-php-ext-install sockets
RUN docker-php-source extract
RUN cd /tmp && git clone https://github.com/openswoole/ext-openswoole.git
WORKDIR /tmp/ext-openswoole
RUN git checkout ${OPENSWOOLE_VERSION}
RUN phpize
RUN ./configure --enable-openssl --enable-hook-curl --enable-http2 --enable-mysqlnd
RUN make
RUN make install

RUN touch /usr/local/etc/php/conf.d/openswoole.ini && \
    echo 'extension=openswoole.so' > /usr/local/etc/php/conf.d/zzz_openswoole.ini

# Redis
# renovate: datasource=github-tags depName=phpredis/phpredis versioning=semver
ENV PHP_REDIS_VERSION="6.1.0"
RUN apk add --no-cache pcre-dev $PHPIZE_DEPS
RUN pecl install redis-${PHP_REDIS_VERSION}
RUN docker-php-ext-enable redis.so