name: Docker image build test

on:
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    concurrency: docker-${{ github.ref }}-${{ matrix.docker-file }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - docker-file: "./Dockerfile.php.8.1"
            image-tag-suffix: "-php8.1"
          - docker-file: "./Dockerfile.php.8.2"
            image-tag-suffix: "-php8.2"
          - docker-file: "./Dockerfile.php.8.3"
            image-tag-suffix: "-php8.3"
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@0d103c3126aa41d772a8362f6aa67afac040f80c # v3

      - name: Login to ghcr
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: "${{ matrix.docker-file }}"
          load: true
          tags: "ghcr.io/sgoettsch/docker-phpstan:latest${{ matrix.image-tag-suffix }}"
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}
